appuser/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf import settings
from django.conf.urls.static import static
from appuser.ussd_views import App_USSD
from .views import *


urlpatterns = [
    #for ussd
    path(f'', App_USSD.as_view(), name="ussd_route"),

    #end for ussd

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

liffton_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header  =  "Integrated Group Information Management System"  
admin.site.site_title  =  "Integrated Group Information Management System"
admin.site.index_title  =  "eGroup"




urlpatterns = [
    path('admin/', admin.site.urls),
    path('ussd/', include('appuser.urls')),
    path('', include('members.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',views.login, name="login"),
    path('login/', views.LoginView.as_view(), name="user_login"),
    #path('login/',views.user_login, name="user_login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name="logout"),
    
    path('member/dashboard/',views.MemberDashboard, name="member_dashboard"),
    path('member/register/',views.RegisterMemberView.as_view(), name="register_member"),
    
    path('applyloan/', views.apply_loan, name='applyloan'),
    path('management/loan-list/', views.loan_list, name='loan_list'),
    path('repayloan/', views.repay_loan, name='repayloan'),
    path('penalty-form/', views.penalty_form, name='penalty_form'),
    path('create_group_announcement/', views.create_group_announcement, name='create_group_announcement'),
    path('create_loan_reminder/', views.create_loan_reminder, name='create_loan_reminder'),
    path('vendor/add/', views.vendor_form_view, name='vendor_form'),
    path('management/add_product/', views.add_product, name='add_product'),
    path('list_vendors/', views.list_vendors, name='list_vendors'),
    path('products/', views.product_list, name='product_list'),

    path('loan-products/', views.display_loan_products, name='loan_products'),
    path('loan-cards/', views.display_loans, name='loan_cards'),
    
    path('management/dashboard/',views.ManagementDashboard, name="management_dashboard"),
    path('management/register/',views.RegisterManagementView.as_view(), name="register_management"),
    path('management/creategroup/',views.CreateGroup, name="creategroup"),
    path('management/list-groups/', views.list_groups, name='list_groups'),
    # path('groups/', views.groups, name='groups'),
    path('groups/', views.groups, name='groups'),
    
       
    path('vendor/dashboard/',views.VendorDashboard, name="vendor_dashboard"),
    path('vendor/register/',views.RegisterVendorView.as_view(), name="register_vendor"),
    
    path('password_change/', views.password_change_view, name='password_change'),
    # path('password_change/done/', views.change_done, name='change_done'),
    
    path('management/trainings/', views.trainings_page, name='trainings_page'),
    path('management/upload_article/', views.upload_article, name='upload_article'),
    path('management/weather/', views.weather_page, name='weather_page'),
    
    path('management/counties/', views. county_list, name='county_list'),
    path('subcounties/', views.subcounty_list, name='subcounty_list'),
    path('wards/', views.ward_list, name='ward_list'),
    
     path('groups/', views.groups, name='groups'),
    


    path('profile/<str:username>/', views.profile, name='profile'),
    path('categories/', views.category_list, name='category_list'),         


    path('loan-line-chart/', views.loan_line_chart, name='loan_line_chart'),
    


]






members/models.py
from django.db import models

from django.contrib.auth.models import User

from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import MaxValueValidator, MinValueValidator


from django.contrib.auth.models import AbstractUser
from django.utils import timezone
length= 255
expiry_days= 255

# Create your models here.



class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_member = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)
    is_management = models.BooleanField(default=False)
 
class County(models.Model):    
  id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=256, null=True) 
  code = models.CharField(max_length=3, null=True) 
  def __str__(self):
        return str(self.name)
      
 
class SubCounty(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    county_id = models.ForeignKey('County', on_delete=models.CASCADE)
    name = models.CharField(max_length=length, blank=True, null=True,)
    lat = models.CharField(max_length=length, blank=True, null=True,)
    lng = models.CharField(max_length=length, blank=True, null=True,)
    category = models.CharField(max_length=length, blank=True, null=True,)
    code = models.CharField(max_length=length, blank=True, null=True,)
    loccode = models.CharField(max_length=length, blank=True, null=True,)

    def __str__(self):
        return '%s' % self.name


class Ward(models.Model):
    county_id = models.ForeignKey('County', on_delete=models.CASCADE)
    subcounty_id = models.ForeignKey('SubCounty', on_delete=models.CASCADE)
    name = models.CharField(max_length=length, blank=True, null=True,)
    lat = models.CharField(max_length=length, blank=True, null=True,)
    lng = models.CharField(max_length=length, blank=True, null=True,)
    category = models.CharField(max_length=length, blank=True, null=True,)
    code = models.CharField(max_length=length, blank=True, null=True,)
    loccode = models.CharField(max_length=length, blank=True, null=True,)

    def __str__(self):
        return '%s' % self.name


class ManagementAdmin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='staffadmins')
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=100, blank=True, null=True)
    national_id = models.CharField(max_length=100, blank=True, null=True)
    telephone = models.CharField(max_length=100, blank=True, null=True)
    bio = models.TextField(max_length=10, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    experience = models.TextField(blank=True, null=True)
    education = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=False, blank=True, null=True)
    banned = models.BooleanField(default=False, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)    
    def __str__(self):
        return self.user.username   




class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=length,null=True, blank=True)
    last_name = models.CharField(max_length=length,null=True, blank=True)
    physical_address = models.TextField(max_length=length,null=True, blank=True)
    national_id = models.CharField(max_length=length,null=True, blank=True)
    primary_phone_number = models.CharField(max_length=length,null=True, blank=True)
    primary_phone_number_provider = models.CharField(max_length=length,null=True, blank=True)
    alternative_phone_number = models.CharField(max_length=length,null=True, blank=True)
    alternative_phone_number_provider = models.CharField(max_length=length,null=True, blank=True)
    year_of_birth = models.CharField(max_length=4,null=True, blank=True)
    gender = models.CharField(max_length=10,null=True, blank=True)
    ward_id = models.ForeignKey(Ward, on_delete=models.CASCADE,null=True, blank=True)
    profile_img = models.ImageField(upload_to='Profile', default='default.png',null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.user.username    
    

class Vendor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True, blank=True, unique=True)
    ward_id = models.ForeignKey(Ward, on_delete=models.CASCADE,null=True, blank=True)
    business_name = models.CharField(max_length=length,null=True, blank=True, unique=True)
    shopping_centre_name = models.CharField(max_length=length,null=True, blank=True)
    contact_person_name = models.CharField(max_length=length,null=True, blank=True)
    contact_person_phone = models.CharField(max_length=length,null=True, blank=True)
    contact_person_password = models.CharField(max_length=length,null=True, blank=True)
    api_key = models.CharField(max_length=length,null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return '%s' % self.business_name

     
  

class Group(models.Model):
    name = models.CharField(max_length=length,null=True, blank=True, unique=True)
    special_code = models.CharField(max_length=4,null=True, blank=True)
    group_type = models.CharField(max_length=length,null=True, blank=True)
    ward_id = models.ForeignKey(Ward, on_delete=models.CASCADE,null=True, blank=True)
    business_activity = models.CharField(max_length=length,null=True, blank=True)
    bank_name = models.CharField(max_length=length,null=True, blank=True)
    bank_services = models.CharField(max_length=length,null=True, blank=True)
    mpesa_paybill = models.CharField(max_length=length,null=True, blank=True)
    mpesa_busines_number = models.CharField(max_length=length,null=True, blank=True)
    mpesa_account_number = models.CharField(max_length=length,null=True, blank=True)
    default_group_id = models.ForeignKey(Member, on_delete=models.CASCADE,null=True, blank=True)
    secretary_name = models.CharField(max_length=length,null=True, blank=True)
    secretary_phone = models.CharField(max_length=length,null=True, blank=True)
    opportunity = models.CharField(max_length=length,null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s' % self.name


class GroupMembers(models.Model):
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE,null=True, blank=True)
    group_id = models.ForeignKey(Group, on_delete=models.CASCADE,null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def _str_(self):
        return str(self.member_id)



class Saving(models.Model):
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE,null=True, blank=True)
    group_id = models.ForeignKey(Group, on_delete=models.CASCADE,null=True, blank=True)
    amount = models.FloatField( validators=[MinValueValidator(0.0), MaxValueValidator(999999999.0)], default=0.0)
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return str(self.create_at)


class SavingLog(models.Model):
    savings_id = models.ForeignKey(Saving, on_delete=models.CASCADE,null=True, blank=True)
    amount = models.FloatField( validators=[MinValueValidator(0.0), MaxValueValidator(999999999.0)], default=0.0)
    transaction_phone = models.CharField(max_length=length,null=True, blank=True)
    transaction_id = models.CharField(max_length=length,null=True, blank=True)
    log_type = models.CharField(max_length=length,null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s' % self.transaction_phone


class Voucher(models.Model):
    code = models.CharField(max_length=length,null=True, blank=True, unique=True)
    create_at = models.DateTimeField(auto_now_add = True)
    expiry =  models.TextField(null=True, blank=True, default=expiry_days)
    amount_equivalent = models.FloatField(null=True, blank=True, default=0.0)
    reviewed =models.BooleanField(null=True, blank=True, default=False)
    voucher_issued =models.BooleanField(null=True, blank=True, default=False)    
    product_issued =models.BooleanField(null=True, blank=True, default=False)
    cancelled =models.BooleanField(null=True, blank=True, default=False)  
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s' % self.name




class LoanProduct(models.Model):
    name = models.CharField(max_length=length,null=True, blank=True)
    description =  models.TextField(null=True, blank=True)
    loan_duration_days = models.IntegerField(null=True, blank=True)
    penalty_rate = models.FloatField( validators=[MinValueValidator(0.0), MaxValueValidator(99.9)], default=0.0)
    interest_rate = models.FloatField( validators=[MinValueValidator(0.0), MaxValueValidator(99.9)], default=0.0)
    product_type = models.CharField(max_length=length,null=True, blank=True)
    borrowing_percentage = models.FloatField( validators=[MinValueValidator(0.0), MaxValueValidator(99.9)], default=0.0)
    borrowing_times = models.IntegerField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add = True)

members/templates/article_list.html
<!DOCTYPE html>
<html>
<head>
    <!-- Add your CSS and other necessary elements here -->
</head>
<body>
    <h1>Article List</h1>
    <ul>
        {% for article in articles %}
            <li>
                <h3>{{ article.title }}</h3>
                <p>{{ article.content|truncatechars:200 }}</p>
                {% if article.document %}
                    <a href="{{ article.document.url }}" target="_blank">Read More</a>
                {% endif %}
            </li>
        {% empty %}
            <p>No articles available.</p>
        {% endfor %}
    </ul>
</body>
</html>

members/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="minimal-theme">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'assets/images/favicon-32x32.png'  %}" type="image/png" />
  <!-- Bootstrap CSS -->
  <link href="{% static 'assets/css/bootstrap.min.css'  %}" rel="stylesheet" />
  <link href="{% static 'assets/css/bootstrap-extended.css'  %}" rel="stylesheet" />
  <link href="{% static 'assets/css/style.css'  %}" rel="stylesheet" />
  <link href="{% static 'assets/css/icons.css'  %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

  <!-- loader-->
	<link href="{% static 'assets/css/pace.min.css'  %}" rel="stylesheet" />

  <title>Integrated Group Information Management System</title>
</head>

<body>

  <!--start wrapper-->
  <div class="wrapper">
    
    {% block content %}


    {% endblock %}



  </div>
  <!--end wrapper-->


  <!--plugins-->
  <script src="{% static 'assets/js/jquery.min.js'  %}"></script>
  <script src="{% static 'assets/js/pace.min.js'  %}"></script>


</body>

</html>

members/templates/categories.html
{% extends 'management/base.html' %}
{% load static %}

{% block content %}

<hr>
<main class="page-content">
    <h1>Categories:</h1>
    <ul>
        {% for category in categories %}
            <li><a href="#">{{ category }}</a></li>
        {% empty %}
            <li>No categories available.</li>
        {% endfor %}
    </ul>

</main>
{% endblock %}

members/templates/group_members.html
{% extends 'management/base.html' %}
{% load static %}

{% block content %}

<hr>
<main class="page-content">
    <h1>Groups and Members:</h1>
    <table>
        <thead>
            <tr>
                <th>Group Name</th>
                <th>Members</th>
            </tr>
        </thead>
        <tbody>
            {% for group in groups %}
                <tr>
                    <td>{{ group.name }}</td>
                    <td>
                        <ul>
                            {% for member in group.member_set.all %}
                                <li>{{ member.name }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2">No groups available.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock %}

members/templates/list_vendors.html
{% extends 'management/base.html' %}
{% load static %}

{% block content %}

<hr>
<main class="page-content">

<body>
    <div class="container">
        <h1>List of Vendors</h1>
        <div class="row">
            
            {% for vendor in vendors %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Name: {{ vendor.contact_person_name }}</h5>
                        <p class="card-text">Business Name: {{ vendor.business_name }}</p>
                        
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>

    
</main>
{% endblock %}

members/templates/loan_cards.html
{% extends 'member/base.html' %}
{% load static %} 

{% block content %}
<hr>
<main class="page-content">
    <h1>loans</h1>
    <div class="card-container">
        {% for loan in loans %}
            <div class="card">
                <h2>{{ loan.loan_type }}</h2>
                <p>Group ID: {{ loan.group_id }}</p>
                <p>Member ID: {{ loan.group_member_id }}</p>
                <p>Loan Product ID: {{ loan.loan_product_id }}</p>
                <p>Amount: {{ loan.amount }}</p>
                <p>Amount Due: {{ loan.amount_due }}</p>
                <p>Duration (days): {{ loan.duration_days }}</p>
                <p>Penalty Rate: {{ loan.penalty_rate }}</p>
                <p>Interest: {{ loan.interest }}</p>
                <p>Interest Rate: {{ loan.interest_rate }}</p>
                <p>Voucher ID: {{ loan.voucher_id }}</p>
                <p>Borrowing Percentage: {{ loan.borrowing_percentage }}</p>
                <p>Borrowing Times: {{ loan.borrowing_times }}</p>
                <p>Approved Date: {{ loan.approved_date }}</p>
                <p>Due Date: {{ loan.due_date }}</p>
                <p>Purpose: {{ loan.purpose }}</p>
                <p>Status: {{ loan.status }}</p>
                <p>Created At: {{ loan.created_at }}</p>
                <p>Updated At: {{ loan.updated_at }}</p>
            </div>
        {% endfor %}
    </div>
</main>


{% endblock %}

members/templates/loan_line_chart.html
{% extends 'management/base.html' %}
{% load static %}

{% block content %}

<hr>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<main class="page-content">

    <h1>Loan Line Chart </h1>
    <canvas id="loan-chart" width="400" height="200"></canvas>

    <script>
        // JavaScript code for creating the line chart
        var ctx = document.getElementById('loan-chart').getContext('2d');
        var dates = JSON.parse('{{ dates|escapejs }}');  
        var amounts = JSON.parse('{{ amounts|escapejs }}');  

        var chart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: dates,
                datasets: [{
                    label: 'Loan Amount',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    data: amounts,
                }]
            },
            options: {
                scales: {
                    x: {
                        type: 'time',
                        time: {
                            unit: 'day', 
                            tooltipFormat: 'YYYY-MM-DD',
                        },
                    },
                    y: {
                        title: {
                            display: true,
                            text: 'Loan Amount',
                        },
                    },
                },
            },
        });
    </script>
</main>
{% endblock %}

members/templates/loan_products.html
{% extends 'member/base.html' %}
{% load static %} 

{% block content %}
<hr>
<main class="page-content">
    <h1>Loan Products</h1>
    <div class="card-container">
        {% for loan_product in loan_products %}
            <div class="card">
                <h2>{{ loan_product.name }}</h2>
                <p>Description: {{ loan_product.description }}</p>
                <p>Loan Duration (days): {{ loan_product.loan_duration_days }}</p>
                <p>Penalty Rate: {{ loan_product.penalty_rate }}</p>
                <p>Interest Rate: {{ loan_product.interest_rate }}</p>
                <p>Product Type: {{ loan_product.product_type }}</p>
                <p>Borrowing Percentage: {{ loan_product.borrowing_percentage }}</p>
                <p>Borrowing Times: {{ loan_product.borrowing_times }}</p>
                <p>Created At: {{ loan_product.created_at }}</p>
                <p>Updated At: {{ loan_product.updated_at }}</p>
            </div>
        {% endfor %}
    </div>
</main>


{% endblock %}

members/templates/loans.html
{% extends 'management/base.html' %}

{% block content %}
<hr>
<main class="page-content">
    

    <div class="container">
        <h2>loan application</h2>
        <form method="post">
            {% csrf_token %}
            <div class="border p-4 rounded">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary px-5">Submit</button>
            </div>
        </form>
    </div>
</main>
{% endblock %}

members/templates/login.html
{% extends 'base.html' %}
{% load static %} 

{% block content %}

<main class="authentication-content">
    <div class="container-fluid">
      <div class="authentication-card">
        <div class="card shadow rounded-0 overflow-hidden">
          <div class="row g-0">
            <div class="col-lg-6 bg-login d-flex align-items-center justify-content-center">
              <img src="{% static 'images/error/login-img.jpg'  %}" class="img-fluid" alt="">
            </div>
            <div class="col-lg-6">
              <div class="card-body p-4 p-sm-5">
                <h5 class="card-title">Sign In</h5>

                {% if message|length > 0 %}
                <div class="alert border-0 bg-warning alert-dismissible fade show py-2">
                  <div class="d-flex align-items-center">
                    <div class="fs-3 text-dark"><i class="bi bi-exclamation-triangle-fill"></i>
                    </div>
                    <div class="ms-3">
                      <div class="text-dark">{{ message }}</div>
                    </div>
                  </div>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% else %}
               <p>&nbsp;</p>
                {% endif %}


                <form class="form-body" action="{% url 'user_login' %}"  method="POST">
                  {% csrf_token %}
                  <div class="d-grid">
                   
                  </div>
                  <div class="login-separater text-center mb-4"> <span>LOGIN</span>
                    <hr>
                  </div>
                    <div class="row g-3">
                      <div class="col-12 ">
                        <label for="inputName" class="form-label">Username</label>
                        <div class="ms-auto position-relative">
                          <div class="position-absolute top-50 translate-middle-y search-icon px-3"><i class="bi bi-person-circle"></i></div>
                          {{ form.username }}                        
                        </div>
                      </div>
                      
                      <div class="col-12">
                        <label for="inputChoosePassword" class="form-label">Enter Password</label>
                        <div class="ms-auto position-relative">
                          <div class="position-absolute top-50 translate-middle-y search-icon px-3"><i class="bi bi-lock-fill"></i></div>
                          {{ form.password }}
                        </div>
                      </div>
                     
                      
                      <div class="col-12">
                        <div class="d-grid">
                          <button type="submit" class="btn btn-primary radius-30">Login</button>
                        </div>
                      </div>
                      <div class="col-12">
                        <p class="mb-0">Don't have an account yet? <br>
                          <a href="{% url 'register_member'%}">Register As A Group Member</a> <br>
                          <a href="{% url 'register_management'%}">Register As Management Staff</a> <br>
                          <a href="{% url 'register_vendor'%}">Register As Vendor</a>
                      
                      </p>
                      </div>
                    </div>
                </form>

                
               
                
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</main>
   



{% endblock %}

members/templates/logout.html
{% extends 'base.html' %}
{% load static %} 

{% block content %}
<p>&nbsp;</p>
<p>&nbsp;</p>
<div class="error-404 d-flex align-items-center justify-content-center">
  <div class="container">
    <div class="card py-5">
      <div class="row g-0">
        <div class="col col-xl-5">
          <div class="card-body p-4">
            <h1 class="display-1"><span class="text-danger">Thank </span><span class="text-primary">You</span><span class="text-success">.</span></h1>
            <h2 class="font-weight-bold display-4">Logged Out</h2>
            <p>You have been logged out of the system
              <br>
            <div class="mt-5"> <a href="{% url 'login' %}" class="btn btn-primary btn-lg px-md-5 radius-30">Login</a>
              <a href="javascript:;" class="btn btn-outline-dark btn-lg ms-3 px-md-5 radius-30">Back</a>
            </div>
          </div>
        </div>
        <div class="col-xl-7">
          <img src="assets/images/error/404-error.png" class="img-fluid" alt="">
        </div>
      </div>
      <!--end row-->
    </div>
  </div>
</div>



{% endblock %}

members/templates/product_list.html
{% extends 'management/base.html' %}
{% load static %}

{% block content %}

<hr>
<main class="page-content">
  <h1>Product List</h1>
  <div class="product-grid">
    {% for product in products %}
      <div class="product-card">
        <img src="{{ product.photo.url }}" alt="{{ product.name }}">
        <h2>{{ product.name }}</h2>
        <p>Category: {{ product.category }}</p>
        <p>Retail Price: ${{ product.retail_price }}</p>
        <p>Wholesale Price: ${{ product.wholesale_price }}</p>
        <p>Description: {{ product.description }}</p>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}

members/templates/reports.html
{% extends 'management/base.html' %}
{% load static %}

{% block content %}

<hr>
<main class="page-content">
 <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <canvas id="loanChart" width="400" height="200"></canvas>
    <script>
        fetch('/monthly_loan_data/')
            .then(response => response.json())
            .then(data => {
                const months = data.map(item => item['approved_date__month']);
                const totalLoans = data.map(item => item['total_loan_amount']);

                const ctx = document.getElementById('loanChart').getContext('2d');
                new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: months,
                        datasets: [{
                            label: 'Monthly Loan Report',
                            data: totalLoans,
                            borderColor: 'blue',
                            backgroundColor: 'rgba(0, 0, 255, 0.2)',
                            fill: true,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        scales: {
                            x: {
                                title: {
                                    display: true,
                                    text: 'Month',
                                },
                            },
                            y: {
                                title: {
                                    display: true,
                                    text: 'Total Loan Amount',
                                },
                            },
                        },
                    },
                });
            })
            .catch(error => {
                console.error('Error fetching data:', error);
            });
    </script>
</main>
{% endblock %}

members/templates/vendor_form.html
{% extends 'management/base.html' %}
{% load static %}

{% block content %}

<hr>
<main class="page-content">
    

    <div class="row">
        <div class="col-xl-9 mx-auto">
            <h6 class="mb-0 text-uppercase">Vendor Form</h6>
            <hr>
            <div class="card">
                <div class="card-body">
                    <div class="border p-4 rounded">
                        <div class="card-title d-flex align-items-center">
                            <h5 class="mb-0">Vendor Details</h5>
                        </div>
                        <hr>
                        <form class="form-body" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <div class="row">
                                <label class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9">
                                    <button type="submit" class="btn btn-primary px-5">Submit Vendor</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}